apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: jenkins-sanity-agent
  name: jenkins-sanity-agent-svc
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 8002
    targetPort: 8002
  selector:
    app: jenkins-sanity-agent
  type: LoadBalancer