apiVersion: v1
data:
  jenkis_uptime.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 71,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green"
                  }
                ]
              },
              "unit": "m"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "percentChangeColorMode": "standard",
            "reduceOptions": {
              "calcs": [
                "lastNotNull"
              ],
              "fields": "",
              "values": false
            },
            "showPercentChange": false,
            "textMode": "auto",
            "wideLayout": true
          },
          "pluginVersion": "12.0.1",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "editorMode": "code",
              "expr": "sum(increase(jenkins_pipeline_up_total{jenkins_url=\"$jenkins\"}[$__range]))*5",
              "instant": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Uptime",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green"
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "m"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 2,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "percentChangeColorMode": "standard",
            "reduceOptions": {
              "calcs": [
                "lastNotNull"
              ],
              "fields": "",
              "values": false
            },
            "showPercentChange": false,
            "textMode": "auto",
            "wideLayout": true
          },
          "pluginVersion": "12.0.1",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "editorMode": "code",
              "expr": "sum(increase(jenkins_pipeline_down_total{jenkins_url=\"$jenkins\"}[$__range]))*5",
              "instant": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Downtime",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "mysql",
            "uid": "P217479990FB70299"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green"
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "end_time"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 160
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "start_time"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 160
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "duration_minutes"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 140
                  },
                  {
                    "id": "custom.align",
                    "value": "center"
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 8
          },
          "id": 4,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": []
          },
          "pluginVersion": "12.0.1",
          "targets": [
            {
              "dataset": "`devops-infra-monitoring`",
              "datasource": {
                "type": "mysql",
                "uid": "P217479990FB70299"
              },
              "editorMode": "code",
              "format": "table",
              "rawQuery": true,
              "rawSql": "SELECT\r\n  start_time,\r\n  end_time,\r\n  ROUND(TIMESTAMPDIFF(SECOND, start_time, end_time) / 60) AS duration_minutes,\r\n  pipeline_url\r\nFROM `devops-infra-monitoring`.JenkinsDowntime\r\nWHERE $__timeFilter(start_time)\r\nAND pipeline_url = \"$jenkins\"\r\nORDER BY start_time;",
              "refId": "A",
              "sql": {
                "columns": [
                  {
                    "parameters": [],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              },
              "table": "JenkinsDowntime"
            }
          ],
          "title": "Jenkins down timeframe",
          "type": "table"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green"
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 7,
            "w": 24,
            "x": 0,
            "y": 16
          },
          "id": 3,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "12.0.1",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "editorMode": "code",
              "exemplar": false,
              "expr": "jenkins_pipeline_success{jenkins_url=\"$jenkins\"}*1",
              "format": "time_series",
              "instant": false,
              "interval": "",
              "legendFormat": "__auto",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Time Graph",
          "transformations": [
            {
              "id": "groupBy",
              "options": {
                "fields": {
                  "Time": {
                    "aggregations": [],
                    "operation": "groupby"
                  },
                  "Value": {
                    "aggregations": [],
                    "operation": "groupby"
                  },
                  "{endpoint=\"metrics\", instance=\"10.139.163.16:8002\", jenkins_url=\"https://cje-il-prod01.devtools.intel.com/epg-sie-ethfwjn/job/Maintenance/job/sanity_pipeline/\", job=\"jenkins-sanity-exporter\", namespace=\"monitoring\", service=\"jenkins-sanity-exporter\"}": {
                    "aggregations": []
                  },
                  "{endpoint=\"metrics\", instance=\"10.139.163.17:8002\", job=\"jenkins-sanity-exporter\", namespace=\"monitoring\", service=\"jenkins-sanity-exporter\"}": {
                    "aggregations": []
                  }
                }
              }
            }
          ],
          "type": "timeseries"
        }
      ],
      "preload": false,
      "schemaVersion": 41,
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "text": "https://cje-il-prod01.devtools.intel.com/epg-sie-ethfwjn/job/Maintenance/job/sanity_pipeline/",
              "value": "https://cje-il-prod01.devtools.intel.com/epg-sie-ethfwjn/job/Maintenance/job/sanity_pipeline/"
            },
            "datasource": {
              "type": "prometheus",
              "uid": "prometheus"
            },
            "definition": "label_values(jenkins_url)",
            "name": "jenkins",
            "options": [],
            "query": {
              "qryType": 1,
              "query": "label_values(jenkins_url)",
              "refId": "PrometheusVariableQueryEditor-VariableQuery"
            },
            "refresh": 1,
            "regex": "",
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "Jenkins Uptime",
      "uid": "8392eea3-f418-4384-879b-98fe81fffbef",
      "version": 1
    }
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard_ipu: "1"
  name: grafana-ipu-jenkins-uptime-dashboard
  namespace: monitoring