apiVersion: v1
kind: Secret
metadata:
  name: jenkins-credentials
  namespace: monitoring
type: Opaque
data:
  # Base64 encoded values
  JENKINS_USERNAME: <base64 user>
  JENKINS_API_TOKEN: <base64 token>
  DB_FERNET_KEY: <base64 fernet>