#!/bin/bash

set -o xtrace

if [ $# -ne 3 ] && [ $# -ne 4 ]
then
	echo "usage is ./run_kw_locally.sh <project_name in KW server> <project_dir> <outputdir> <mev_project>"
	echo "example"
	echo "./run_kw_locally.sh MEV_TS_IMC_INFRA ~/mev_ts_repo/sources/imc/mev_infra outputdir MEV_TS"
	exit 1
fi

current_dir=$(pwd)

# Begin script in case all parameters are correct
project="$1"
projectdir="$2"
outputdir=$3
mev_project=$4

echo "project name is $project"
echo "project dir is $projectdir"
echo "output dir is $outputdir"
echo "mev_project dir is $mev_project"

KW_SERVER=klocwork-igk2.devtools.intel.com
KW_SYNC_SERVER=klocwork-igk2.devtools.intel.com
KW_SERVER_PORT=8080
KW_LICENSE_SERVER=klocwork05p.elic.intel.com
KW_LICENSE_SERVER_PORT=7500

set LM_LICENSE_FILE=$KW_LICENSE_SERVER_PORT@$KW_LICENSE_SERVER

echo "Run kwcheck create to create a local Klocwork project that is connected to the server project"
if ! command -v kwcheck &> /dev/null
then
	if [ -f /mnt/ci_tools/klocwork_client/bin/kwcheck ]
	then
		export PATH=$PATH:/mnt/ci_tools/klocwork_client/bin
	else
		echo "kwcheck not found in PATH, please install"
		exit 1
	fi
fi
cd $projectdir
rm -rf .kwlp .kwps
echo "*************** Create project ***************"
kwcheck create --url https://$KW_SERVER:$KW_SERVER_PORT/$project -pd .kwlp -sd .kwps
if [ $? -ne 0 ]; then
	echo "Failed to create KW local project, please run kwauth to login..."
	echo "kwauth --url https://$KW_SERVER:$KW_SERVER_PORT"
	exit 1
fi

echo "Run kwinject to generate the build specification"
echo "*************** Run KW inject ($0) ***************"
if [ "$project" == "MEV_NSL" -o "$project" == "MEV_TS_LINUX_NSL" ]
then
	# kwinject --output kwinject.out --overwrite sh build/nsl_build_release_imc.sh
	# kwinject --output kwinject.out sh build/nsl_build_release_imc_llvm.sh
	if [ $mev_project == "MEV_TS" ];
	then
		kwinject --output kwinject.out --overwrite sh mev_ts_imc_build_all
	else
		kwinject --output kwinject.out --overwrite sh mev_imc_build_all.sh
	fi
elif [ "$project" == "MEV_TS_LINUX_ATF" -o "$project" == "MEV_TS_IMC_INFRA" -o "$project" == "MEV_TS_LINUX_USERSPACE" -o "$project" == "MEV_TS_LINUX_PHYSS" ] # ADD MMG PROJECTS HERE ALSO
then
	kwinject --output kwinject.out --overwrite sh mev_ts_imc_build_all.sh # this is diffrent build script for ts-linux components
elif [ "$project" == "MMG_INFRA" -o "$project" == "MMG_USERSPACE" -o "$project" == "MMG_ATF" -o "$project" == "MMG_IMC_UBOOT" ] # ADD MMG PROJECTS HERE ALSO
then
	kwinject --output kwinject.out --overwrite sh mmg_imc_build_all.sh # this is diffrent build script for mmg components
elif [ "$project" == "MEV_TS_LINUX_CP" ]
then
	kwinject --output kwinject.out --overwrite sh mev_build_imccp.sh clean
else
	kwinject --output kwinject.out --overwrite sh mev_imc_build_all.sh
fi

echo "Run kwcheck sync"
echo "*************** Run KW sync ***************"
kwcheck sync --verbose -pd .kwlp -sd .kwps

echo "Run kwcheck to do the analysis. Use the build spec created in the kwinject step"
echo "*************** Run KW check ***************"
kwcheck run -b kwinject.out -pd .kwlp -F detailed --report $outputdir/report_$project.txt

echo "Read the report file generated by kwcheck run and check for errors"
echo "*************** Parse KW result ***************"
total=$(grep -oP '^(\d+) Total Issue' $outputdir/report_$project.txt |awk '/Total/{print $1}')
if [[ -z "$total" ]]; then
	echo "No output found in report."
	exit 1
fi
if [ $total -gt 0 ]; then
	echo "Total Issue found: $total"
	exit 1
fi
echo "*************** KW scan passed ***************"
